language: node_js
secure: TwT8EGKBRVRZ3xEL1ipzw0pA4vcsmMmQmIbB+fJfoF6qNJ9+nwXE7+XxouW/AXLkuNzS2/fohxTRZHZ8WqYsbXlJLEhhRdtvYPgY2P49JKRJ2T94L21xgBPd/jlZUCha0+9gBm1R1pFnAH5NPuU1KbnhiKVaXMGaMxP3dLWU5tuEBrJaQeYm3sUlA2MmggizGTJoCBLuDU4P5003SY697pdZKAowz3yapDAxl+QtbaazdSzkRBa4HvsQQ+DWudEWBxH+oTZ6wwDYJQeunraK62o/AkiC9DM93xmke6Ng+isWTLe6OJwTiIq6jCopmYE2dSuY/SkTn7YT70ObHi+KbpT21opU62xTKXVDzgU2l3pri5K4VaPzbzklUvFo/iDSbRAdpNdzg1MbzFfYmcUpQy/XiwkcbcCRJ42zmTsIiAmZZ51cG52/31QjT/RxPb+i5tYo61LidFO4CmJe4ZltVbZGTQQHKSjGvFQGx+KGGU60+1RHWNdmr0eyFM7zH61Z49uVIKtbAz6Ds3e9DsUKEJ/+CbP/ZIxJbYG0Xeb9rxJFS34D3d+wVb5bmaAu1P3zT7mjw94cK1W4ShZ2PtFq60HveKFG7+RZ/Qmx57g3FHKKCKa11mchb6l/V6Abai1QtrghsVpS+ui0W1u6o7DdAeU4cnkzdOyDEFaYKIDWDvc=
before_script:
- npm install -g gulp-cli
script: gulp build
deploy:
- provider: script
  skip_cleanup: true
  script: "./.travis-deploy.sh"
  on:
    branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_fb17a912150b_key -iv $encrypted_fb17a912150b_iv
  -in ed25519.enc -out ed25519 -d
